### ISSUE TITLE
可以引用吗？

### ISSUE THREAD

**Issue by L-M-Sherlock** [Quorafind/SMDoc-CN#1]
您好，我想在文章里引用《20 条基本规则》，并把里面的例子改成高考相关的材料，请问我需要用什么格式吗？以及部分翻译内容我想进行修改，请问在引用的时候可以吗？

**Comment by SuperDaniel-cn** [comment]
原文在这里，希望对你有用。[The 20 rules of formulating knowledge in learning](http://super-memory.com/articles/20rules.htm)

**Comment by Quorafind** [comment]
@L-M-Sherlock 如果你是商业使用，请在文末标注仓库名、地址以及原文地址。谢谢。引用格式随意。
